In [ ]:
#1. What is a Python library? Why do we use Python libraries?
A Python library is a collection of pre-written code, functions, and modules that
can be imported into a Python script or program. These libraries provide a set of tools and functionalities 
that help developers perform common tasks without having to write code from scratch. Python libraries are an 
integral part of the Python programming ecosystem and contribute to the language's versatility and efficiency.

Code Reusability: Python libraries contain reusable code components that can be easily incorporated into new 
projects. This promotes efficient development by avoiding the need to recreate common functionalities.

Time Efficiency: By utilizing pre-existing libraries, developers can save time on coding and testing. Libraries
are often well-tested and optimized, reducing the time required to implement specific features or solve particular 
problems.

Community Contributions: Many Python libraries are open-source, developed and maintained by a community of programmers. This collaborative approach fosters the sharing of knowledge and expertise, allowing developers to benefit from collective efforts.

Specialized Functionality: Python libraries are designed to address specific tasks or domains. For example, libraries like NumPy and pandas are tailored for data manipulation and analysis, while TensorFlow and PyTorch are specialized for machine learning. Using these libraries allows developers to leverage expertly crafted tools for their specific needs.

Standardization: Libraries often follow established coding conventions and best practices. This ensures a level of standardization, making it easier for developers to work with code written by others and enhancing the overall maintainability of projects.

Enhanced Performance: Many Python libraries are implemented in lower-level languages, such as C or C++, to optimize performance. Developers can benefit from these optimizations without needing to write low-level code themselves.

Ecosystem Integration: Python libraries seamlessly integrate with the broader Python ecosystem. This interoperability allows developers to combine different libraries to create comprehensive solutions for various applications.


In [ ]:
#2. What is the difference between Numpy array an^ List?
NumPy arrays and Python lists are both used to store collections of items, but they have several key differences in terms of functionality, performance, and usage. Here are some of the main distinctions between NumPy arrays and lists:

Data Type:

NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and manipulation of large datasets.
List: Python lists can contain elements of different data types. This flexibility is useful in certain situations but can lead to less efficient performance when working with large datasets or numerical computations.
Performance:

NumPy Array: NumPy arrays are more efficient for numerical operations and large datasets. NumPy is implemented in C and allows for vectorized operations, which means that operations are performed on entire arrays at once, leading to improved performance.
List: Lists are more general-purpose and are less efficient than NumPy arrays for numerical operations. Lists require more memory and may be slower when working with large datasets or performing numerical computations.
Functionality:

NumPy Array: NumPy provides a wide range of mathematical operations and functions that can be applied directly to arrays, such as matrix multiplication, linear algebra operations, statistical functions, and more.
List: Lists offer basic operations for general-purpose programming but lack the extensive mathematical functionality provided by NumPy.


In [7]:
'''3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

import numpy as np
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(np.shape(arr),np.size(arr),np.ndim(arr))
'''4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr1=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(arr1[0])
'''5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
ak=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
element = arr1[2, 3]
print(element)

(3, 4) 12 2
[1 2 3 4]
12


In [10]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
import numpy as np
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
# Extracting all odd-indexed elements
odd_indexed_elements = arr1[ :,1::2].flatten()
print(odd_indexed_elements)

[ 2  4  6  8 10 12]


In [14]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
arr=np.random.randint(0,2,(3,3))
print(arr)

[[1 0 0]
 [0 0 1]
 [1 0 0]]


In [ ]:
8. Describe the difference between np.random.randand np.random.randn?
np.random.rand produces random numbers uniformly distributed between 0 and 1.
np.random.randn produces random numbers from a standard normal distribution with mean 0 and standard deviation 1.

In [22]:
'''9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(np.ndim(arr))
k=np.expand_dims(arr,axis=0)
print(np.ndim(k))

2
3


In [23]:
'''10. How to transpose the following array in NumPy?
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
'''11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A'''
import numpy as np
m1=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
m2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print(m1*m2)
print(m1@m2)
print(m1+m2)
print(m2/m1)

In [35]:
'''12. Which function in Numpy can be used to swap the byte order of an array?
The function in Numpy that can be used to swap the byte order of an array is numpy.ndarray.byteswap. This 
function swaps the byte order of the array's data if the machine's native byte order is different from 
the array's byte order.'''
import numpy as np
x = np.array([1, 2, 3], dtype=np.int16, order='F')
print("Original array:")
print(x)
print("Byte order: ", x.dtype.byteorder)
x_swapped = x.byteswap()
print("Swapped array:")
print(x_swapped)
print("Byte order: ", x_swapped.dtype.byteorder)

Original array:
[1 2 3]
Byte order:  =
Swapped array:
[256 512 768]
Byte order:  =


In [ ]:
13. What is the significance of the np.linalg.inv function?
The numpy.linalg.inv function in Python is used to compute the inverse of a square matrix. 
The inverse of a matrix A is denoted as A^-1, and it is a matrix such that when A is multiplied by its inverse,
the result is the identity matrix.
The inverse of a matrix A is defined only if A is a square matrix and its determinant is not zero. 
If the determinant of A is zero, then A is a singular matrix and does not have an inverse.
The numpy.linalg.inv function uses LU decomposition to compute the inverse of a matrix. The LU decomposition 
factorizes a matrix into a product of a lower triangular matrix and an upper triangular matrix, which can then 
be used to efficiently compute the inverse.

import numpy as np

# Create a numpy array
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Print the original matrix and its inverse
print("Original matrix:")
print(A)
print("Inverse of A:")
print(A_inv)

# Verify that A * A_inv is the identity matrix
I = np.dot(A, A_inv)
print("A * A_inv:")
print(I)

In [ ]:
14. What does the np.reshape function do, and how is it used?
The numpy.reshape function in Python is used to reshape an existing numpy array into a new shape while 
preserving its data. The numpy.reshape function takes two arguments: the array to be reshaped and the 
desired shape of the new array.
By specifying the new shape as a tuple of integers, where the length of the tuple must match the total number 
of elements in the array.
By specifying the new shape as a tuple with -1 in one or more positions, 
indicating that the corresponding dimension can be inferred from the length of the array
and the other dimensions specified.

In [ ]:
15. What is broadcasting in Numpy?
Broadcasting in NumPy is a set of rules that allows numpy to work with arrays of different shapes when 
performing arithmetic operations. Broadcasting is a powerful feature that enables you to perform arithmetic 
operations between arrays of different shapes, as long as they are compatible.